### ISSUE TITLE
Any plans to publish MathJSON on NPM? Its quite cumbersome to build it yourself...

### ISSUE THREAD

**Issue by mindreframer** [cortex-js/math-json#3]
First, thank you for this very interesting library! 

It would be really good if one could install it by just using NPM, what is the reason to keep it unpublished? Still not ready for prime-time?

**Comment by arnog** [comment]
Thank you! The project is ready for prime time, although there are many extensions to it I have planned.

It is available on npm at https://www.npmjs.com/package/@cortex-js/math-json

I haven't published frequent updates, as there doesn't seem to be a lot of interest in the project yet. As you can see it's got a single star on github...

**Comment by mindreframer** [comment]
Hey @arnog, thanks for the quick response! Wow, so it's already published! And you've updated the readme! 👍  

Going off to play with new shiny things... ;)

**Comment by arnog** [comment]
Feel free to star the repo when you get the chance...

**Comment by mindreframer** [comment]
Done : )
