### ISSUE TITLE
Typescript Types not available + requiring '@cortex-js/math-json' does not work with Jest + typescript

### ISSUE THREAD

**Issue by mindreframer** [cortex-js/math-json#4]
Hey @arnog, what would be the recommended way to use math-json with Typescript? 

Currently my editor complains... 

Also: Jest with Typescript does not like the js files in the dist folder: 

```
 FAIL  src/util/mathjson.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/roman/Desktop/work/playground/node_modules/@cortex-js/math-json/dist/math-json.js:7745
    export { ComputeEngine, LatexSyntax, evaluate, format, parse, parseCortex, serialize, serializeCortex };
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```

Test-file: 
```
import { expect } from '@jest/globals'
import { parse, serialize } from '@cortex-js/math-json'


describe('something', () => {
  it('should ', () => {
    console.log(parse('\\frac{\\pi}{2}'))
  })
})

```

**Comment by arnog** [comment]
The `dist` folder contains a `types` subdirectory, which is the Typescript declaration files for MathJSON.

Which editor are you using and  how is it complaining?

It looks like `jest` is not configured to load a Javascript module. 

Have you tried:
`
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
`
?

**Comment by mindreframer** [comment]
Hmm... Nope, also not working with the help from Jest FAQ...
I have made a little reproduction here: 

- https://github.com/mindreframer/mathjson-typescript-bug

I hope this helps to narrow it down. This is a slightly unusual setup (vite.js + esbuild-jest), but any other lib I use (including Mathlive, I had to mock CSS files) works fine with TS + Jest. 

I guess I'm hitting some early adopter issues, but this is a good thing!

Thanks and have a good weekend!

**Comment by arnog** [comment]
Thanks, that's super useful.

It turns out there is a configuration problem in the package.json of the module. Working on a fix now.

**Comment by arnog** [comment]
OK, should work now. Let me know if you run into some other problems...

**Comment by mindreframer** [comment]
@arnog AWESOME! it works flawlessly! Thank you very much!
